spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: toor
    url: jdbc:mysql://localhost:3306/springssf
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true